
SERVER:
  protocol: http
  host: localhost
  name: Simple Server Template
  port: 3333
  # Should we display docs and swagger?
  docs: true
  # TODO: For file/report/email generation
  tmpDir: tmp

LOGS:
  debug: true # Shows errors in console while running server
  directory: logs/
  level: info

DB:
  MARIADB:
    name: test
    host: localhost
    user: root
    password: root

PATHS:
  api: /api
  info: /admin/info
  healthcheck: /admin/status
  ## TODO: Add Log Output endpoint
  logs: /admin/logs

## TODO: Protect healthcheck and logs behind these?
AUTHORIZATION:
  ADMIN:
    enabled: false # set to true for production
    id: root
    password: root
# OAUTH: (TODO: for connecting to other services)
# SSO: (TODO: for external session management)

## TODO: Add controller/dataservice that uses one of these
EXTERNAL_SERVICES:
  EXAMPLE_API:
    protocol: http
    host: example.com
    port: 4444
    path: /api/v1
    healthcheck:
      port: 4444
      path: /example/admin/status
    cacheEnabled: false
    cacheExpiration: 60
