name: Doc Build and Wiki Sync on Merge to `master`

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generate Demo and Docs
      run: |
        npm install -D
        npm run doc

    - name: Commit Demo and Docs
      run: |
        git config --local user.email "devlinjunker@gmail.com"
        git config --local user.name "GitHub Action"
        git commit -m "Docsite and Demo Build on Push to Master" -a

    - name: Push changes to Docs
      uses: ad-m/github-push-action@master
      with:
        # Have to do this trickery because action requires GITHUB_TOKEN (I've been using GH_PAT on my account)
        github_token: ${{ secrets.GITHUB_TOKEN }}${{ secrets.GH_PAT }}


    - name: Collect READMEs into temp directory
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: node ./scripts/actions/collect-wiki.js

    # from: https://github.com/marketplace/actions/wiki-page-creator-action
    - name: Upload READMEs to Wiki
      uses: docker://decathlon/wiki-page-creator-action:latest
      env:
        ACTION_MAIL: devlin.junker@gmail.com
        ACTION_NAME: devlinjunker
        GH_PAT: ${{ secrets.GH_PAT }}
        MD_FOLDER: ./wiki
        OWNER: devlinjunker
        REPO_NAME: template.hapi.rest
        SKIP_MD: README.md
